image: "rust:latest"
variables:
  RUSTFLAGS: -D warnings
before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential pkg-config libobs-dev lsb-release wget software-properties-common gnupg2 qt5-default qt5-qmake qtbase5-dev cmake curl
  - bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
  - wget -O /usr/include/obs/obs-frontend-api.h https://raw.githubusercontent.com/obsproject/obs-studio/a38cd03e065efbc863bc897012900938aa70beb3/UI/obs-frontend-api/obs-frontend-api.h

stages:
  - test

cache: &global_cache
  key: ${CI_COMMIT_BRANCH}
  paths:
    - bindings/
    - $CARGO_HOME
    - target/
  policy: pull

test stable:
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy
    - cargo test --workspace
  cache:
    <<: *global_cache
    policy: pull-push

test nightly:
  allow_failure: true
  stage: test
  script:
    - rustup toolchain add nightly
    - cargo +nightly test --workspace