# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: 'BuildLinux'
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - script: sudo apt-get install -y meson ninja-build libc-dev-bin libc6-dev git build-essential checkinstall cmake obs-studio qtbase5-dev libobs-dev
        displayName: 'Install OBS dependencies'
      - script: sudo wget -O /usr/include/obs/obs-frontend-api.h https://raw.githubusercontent.com/obsproject/obs-studio/25.0.0/UI/obs-frontend-api/obs-frontend-api.h
        displayName: 'Download OBS frontend header'
      - script: |
          meson _build
          cd _build && ninja
        displayName: 'Build using Meson + Ninja'
