name: ci_meson
on: push
jobs:

  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Install OBS dependencies
      run: sudo apt-get -qq update && sudo apt-get install -y meson ninja-build libc-dev-bin libc6-dev git build-essential checkinstall cmake obs-studio qtbase5-dev libobs-dev
    - run: meson setup build
      env:
        CC: gcc
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt
